use sakila;

# List the number of films per category.

SELECT count(film_id), name
FROM film_category fc
INNER JOIN category c
USING (category_id)
INNER JOIN film
USING (film_id)
GROUP BY name;

#Retrieve the store ID, city, and country for each store.

SELECT store_id, city, country
FROM store
INNER JOIN address
USING (address_id)
INNER JOIN city
USING (city_id)
INNER JOIN country
USING (country_id);

#3.  Calculate the total revenue generated by each store in dollars.

SELECT store_id, sum(amount) as total_revenue
FROM store
INNER JOIN staff
USING (store_id)
INNER JOIN payment
USING (staff_id)
GROUP BY store_id;

#4. Determine the average running time of films for each category.

SELECT name, sum(length)
FROM film_category
INNER JOIN category
USING (category_id)
INNER JOIN film
USING (film_id)
GROUP BY name;